### ISSUE TITLE
Access Module - Global Rules - Pause Rules Toggle On/Off

### ISSUE THREAD

**Issue by TJ-Everett** [thrackle-io/forte-rules-engine-v1#15]
This ticket was created from design meeting 6/26/23 in order to implement functionality to toggle pause rules in App Manager to keep parity with the access Tier and Risk rules. 

Pause rules check should be turned on/off via boolean in protocolApplicationHandler.sol.

**Comment by ShaneDuncan602** [comment]
This rule should be fairly easy. It's just a matter of adding toggle functionality into the ProtocolApplicationHandler to only turn on the rules when they add a pause window. There is already a cleanup function. This should be modified to turn off the rule when no pause rules exist.

**Comment by TJ-Everett** [comment]
The above comment will be possible after audit changes [from this ticket](https://github.com/thrackle-io/tron/pull/48) are merged.

**Comment by TJ-Everett** [comment]
This will need to have the branch updated with the most updated version of external once audit tickets are finished and then have any conflicts resolved. 
Currently the bool logic is implemented in the ticket and should only need .5/1 days to resolve once started.
