### ISSUE TITLE
Audit - Starting time for rule activation (1)

### ISSUE THREAD

**Issue by ShaneDuncan602** [thrackle-io/forte-rules-engine-v1#23]
For detailed findings on this issue, reference [Finding 1](https://drive.google.com/file/d/1YEockBPB2IcMVV3iLXCRsipiSDLbd3Rp/view?ts=64b5552c) in the document.

Fix Plan

- Create a common function so that the start timestamp can be created the same way for all rolling period rule checks.
- NOTE: May need to create two, one that takes just the hour and one that takes a full timestamp.
- All of the date logic should be similar and run through common functions.
- Also, Purchase limit needs to accept midnight

More information can be found in this [message thread](https://thrackle.slack.com/archives/C05AQKVNENR/p1690557542858299)

These changes should be done in branch, TOB-THR-1, cut from External.

**Comment by jjbailey-io** [comment]
**Decision needed:**

1.  Do we only fix the faulty sections, or standardize all date items? 
2. Do off-chain processing of the start time period so the absolute time is submitted instead of the period that is then calculated on-chain? Only viable if UI exists.

**Comment by ShaneDuncan602** [comment]
Final determination was made to address via the short term fix suggested by ToB.

**Comment by oscarsernarosero** [comment]
These rules should be checked as well:

- PurchaseRule
- SellRule

In these, the time is treated in (0-11) hour format, but it should be (0-23)

**Comment by ShaneDuncan602** [comment]
ready for merge
