### ISSUE TITLE
Audit - Lack of contract existence checks in external calls (11)

### ISSUE THREAD

**Issue by ShaneDuncan602** [thrackle-io/forte-rules-engine-v1#33]
For detailed findings on this issue, reference [Finding 11](https://drive.google.com/file/d/1YEockBPB2IcMVV3iLXCRsipiSDLbd3Rp/view?ts=64b5552c) in the document.

Fix Plan
- Add check for contract existence(of the facet) prior to rule creation and checks.
- Add test to ensure a self-destructed facet does not still function.

These changes should be done in branch, TOB-THR-11, cut from External.

**Comment by jjbailey-io** [comment]
**Decision needed:** Are the gas implications worth it? We recommend not doing this.

**Comment by jjbailey-io** [comment]
Shane Duncan: 

> Another question, this concerns TOB-THR-11. This is listed as High severity and I’m wondering if our deployment model and management would make a difference here. We agreed that this is not an issue as long as the facet is correctly removed. It would only be a problem if the facet is self-destructed.
> These two diamonds will be managed in-house and facets are not intended to be self-destructed. If a facet must be removed it will be done via a script that invokes diamondCut on the facet with an action of Remove. Additionally, only the protocolOwner may perform this action.
> Any logic added to all the rule checks introduces more gas consumption. We would like to avoid that if possible so we would  prefer to leave as is. Is this doable? If there are too many potential pitfalls there, we may be able to pursue a fix during DiamondCut where the source could be scanned for selfdestruct to ensure that a facet with selfdestruct capabilities could never be added to the diamond.


Michael Colburn

> Hey Shane, thanks for pointing that out! :smile: We took another look there as well with the extra context and agree that those should be effective compensating controls. We're planning to drop the severity there to informational as well as bump up the difficulty to high


No further action necessary.
