### ISSUE TITLE
Audit - Improper event emission (13)

### ISSUE THREAD

**Issue by ShaneDuncan602** [thrackle-io/forte-rules-engine-v1#35]
For detailed findings on this issue, reference [Finding 13](https://drive.google.com/file/d/1YEockBPB2IcMVV3iLXCRsipiSDLbd3Rp/view?ts=64b5552c) in the document.

Fix Plan
- Add logic to ensure that the event is only emitted when the state is actually changed. 
- Repeat this in the other mentioned contracts: AppRuleDataFacet and Fees

These changes should be done in branch, TOB-THR-13, cut from External.

**Comment by jjbailey-io** [comment]
**Input from DOOM?** Should we emit events for attempts to remove a tag (in the case of it not present in the list), or only when it's actually removed?

**DOOM:** We already account for this, if we try to remove something that doesn't exist, it's not there so it doesn't care. Recommend just fixing the issue.

**Comment by ShaneDuncan602** [comment]
Ready for merge

**Comment by ShaneDuncan602** [comment]
This issue was reopened because ToB added more to it. See [Week 2 Finding  13](https://drive.google.com/file/d/1Bb3Bb9IVtHyieh0uXDiBDpRM5t_2DiZ6/view?usp=sharing) for more detail.

Additionally, remove HandlerConnectedForUpgrade from ProtocolERC721 connectHandlerToToken and replace with HandlerConnected.

This should be addressed in the same branch it was started in.
