### ISSUE TITLE
Audit - Unbounded loop in getAccTotalValuation could result in denial of service (14)

### ISSUE THREAD

**Issue by ShaneDuncan602** [thrackle-io/forte-rules-engine-v1#36]
For detailed findings on this issue, reference [Finding 14](https://drive.google.com/file/d/1YEockBPB2IcMVV3iLXCRsipiSDLbd3Rp/view?ts=64b5552c) in the document.

Fix Plan
- Add a maximum number of expected NFT's to the protocolERC721Handler
- Add getters and setters for this variable but default it to 100.
- Get total number of NFT's, if the user has more than the above variialbe, use the collection prices instead trying to retrieve each of the tokenId prices.

These changes should be done in branch, TOB-THR-14, cut from External.

**Comment by jjbailey-io** [comment]
Decision: is this scenario valid and do we want to do anything about it?

**Comment by ShaneDuncan602** [comment]
Solution was discussed, see the Fix Plan above.
