### ISSUE TITLE
Create a key management policy/procedure

### ISSUE THREAD

**Issue by jjbailey-io** [thrackle-io/forte-rules-engine-v1#43]
A key management strategy for the management of the EVM Protocol on Polygon should be documented in confluence and tested to include:

- Company policy/procedure
    - Who are the responsible parties?
    - How to deploy the protocol?
    - How are changes proposed?
- Technology used (and tested)
- Steps outlining:
    - How to setup a multisig wallet
    - How do deploy using a multisig (how do we notify multisig parties?)
    - How to propose a change

**Comment by TJ-Everett** [comment]
Is this consolidating this info into a singular doc? Is this creating the policy for Thrackle? Combo of the two? Also will this be public facing (i.e. given to customers as "here is our guidelines for key management")?

**Comment by jjbailey-io** [comment]
This would be the internal Thrackle policy on the management of the protocol we deploy and manage.

**Comment by TJ-Everett** [comment]
[Policy Doc](https://thracklelabs.atlassian.net/wiki/spaces/THRACKLELA/pages/166330377/Thrackle+Key+Management+Policy+and+Procedures)

**Comment by TJ-Everett** [comment]
Additional testing needed: 
Deploy protocol through a hardware wallet via foundry + deploy scripts 
After fresh Mumbai deployment - test transferOwnership() to multiSig on Mumbai
