### ISSUE TITLE
Audit - Missing validation in publicly callable safeMint (16)

### ISSUE THREAD

**Issue by ShaneDuncan602** [thrackle-io/forte-rules-engine-v1#52]
For detailed findings on this issue, reference [Week 2 Finding 16](https://drive.google.com/file/d/1Bb3Bb9IVtHyieh0uXDiBDpRM5t_2DiZ6/view?usp=sharing) in the document.

Fix Plan
- TBD

These changes should be done in branch, TOB-THR-16, cut from External.

**Comment by ShaneDuncan602** [comment]
Not sure if this is actually an issue or not. The example code is well documented with the options that devs have.

**Comment by ShaneDuncan602** [comment]
This is something that Erik wanted to talk about.

**Comment by jjbailey-io** [comment]
> Deemed a non-issue. App Admins have full control over their minting permissions. This is thoroughly documented in the code and several examples are included to aid them in choosing their best permissions strategy.

**Comment by ShaneDuncan602** [comment]
This is related to the npm ticket so it is being reopened. #57
