### ISSUE TITLE
Audit - Inconsistent implementation of risk processing(17)

### ISSUE THREAD

**Issue by ShaneDuncan602** [thrackle-io/forte-rules-engine-v1#53]
For detailed findings on this issue, reference [Week 2 Finding 18] 
 (https://drive.google.com/file/d/1Bb3Bb9IVtHyieh0uXDiBDpRM5t_2DiZ6/view?usp=sharing)-> 17 in the document.

Fix Plan
- Make sure that all risk logic is consistent and matches the logic that is already in the comments.

These changes should be done in branch, TOB-THR-17, cut from External.

**Comment by TJ-Everett** [comment]
updated to issue 17 to stay consistent with ToB final report
