### ISSUE TITLE
Audit - Batch minting breaks ProtocolERC721Handler rule handling(18)

### ISSUE THREAD

**Issue by ShaneDuncan602** [thrackle-io/forte-rules-engine-v1#54]
For detailed findings on this issue, reference [Week 2 Finding 18](https://drive.google.com/file/d/1Bb3Bb9IVtHyieh0uXDiBDpRM5t_2DiZ6/view?usp=sharing) in the document.

Fix Plan
- Remove hard-coded batchsize value in checkAllRules
- Modify transferValuation to work with the batchsize by adjusting the amount accordingly.

These changes should be done in branch, TOB-THR-18, cut from External.

**Comment by ShaneDuncan602** [comment]
Ready for merge

**Comment by TJ-Everett** [comment]
updated to issue 18 to stay consistent with ToB final report
