### ISSUE TITLE
Audit - Access level zero rule checks can be bypassed(19)

### ISSUE THREAD

**Issue by ShaneDuncan602** [thrackle-io/forte-rules-engine-v1#55]
For detailed findings on this issue, reference [Week 2 Finding 20](https://drive.google.com/file/d/1Bb3Bb9IVtHyieh0uXDiBDpRM5t_2DiZ6/view?usp=sharing) ->19 in the document.

Fix Plan
- Change logic as suggested so that AccessLevel0 rule may not be bypassed for anything except AMM.

These changes should be done in branch, TOB-THR-19, cut from External.

**Comment by TJ-Everett** [comment]
After exploring the issue further I have written up my finding [here](https://docs.google.com/document/d/1wXHaF1X_e2SXamUK3LKXBvlYHfTqKL8gRKiZIlUwM1w) and want to confirm with the full team before moving forward.

**Comment by TJ-Everett** [comment]
updated to issue 19 to stay consisted with ToB final report
