### ISSUE TITLE
Investigate NPM installation of protocol files for client implementation

### ISSUE THREAD

**Issue by jjbailey-io** [thrackle-io/forte-rules-engine-v1#57]
***CODE SHOULD NOT BE MADE PUBLIC TO DO THIS***

Investigate how to setup the tron repository files to be installed into a client's machine via npm utilizing hardhat. This would only need to be the files a client would need to implement the protocol.  If this requires code to be made public, discuss the steps w/ @jjbailey-io. 

***CODE SHOULD NOT BE MADE PUBLIC TO DO THIS***

- [ ] Investigate how to install via npm
- [ ] Implement installation via npm
- [ ] Update the deployment guides to incorporate utilizing npm.

**Comment by jjbailey-io** [comment]
After doing some research it appears that this is possible via a "Team" NPM account. Cost is $7/user/month. The package can be organizationally scoped which keeps it private. We should test this with a bogus library prior to actually publishing our code  to make sure it stays private. 

Resources:
- About private npm packages: https://docs.npmjs.com/about-private-packages
- Pricing: https://www.npmjs.com/products
- Scopes (used to say who can access the library) https://docs.npmjs.com/about-scopes
- Creating and publishing private packages
    -  https://docs.npmjs.com/creating-and-publishing-private-packages
    - https://betterprogramming.pub/create-your-first-solidity-library-and-publish-it-on-npm-df5578cde8cb

Create an npmljs.com user account and notify @jjbailey-io  of your account and he will add you to the organization.

**Comment by oscarsernarosero** [comment]
"...and notify @jjbailey-io of your account and he will add you to the organization." lol

**Comment by oscarsernarosero** [comment]
Created the bogus library at https://github.com/thrackle-io/thrackle_npm, and the **npm** package can be seen here https://www.npmjs.com/package/@thrackle-io/npm @jjbailey-io

**Comment by oscarsernarosero** [comment]
Final additions were made in https://github.com/thrackle-io/tron/pull/115
