### ISSUE TITLE
All Modules - Create version variables and associated functions

### ISSUE THREAD

**Issue by ShaneDuncan602** [thrackle-io/forte-rules-engine-v1#58]
Create a string variable to store the version information. This must be a string in order to capture semantic versioning, ie 1.0.0. 

This should be added to:
1. All Handlers
2. AppManager
3. RuleStorageDiamond
4. RuleProcessorDiamond

**Comment by jjbailey-io** [comment]
The starting version should be v0.0.6. #41 will increment the version to v1.0.0 when ready.
