### ISSUE TITLE
Tron Versioning Process

### ISSUE THREAD

**Issue by TJ-Everett** [thrackle-io/forte-rules-engine-v1#59]
We will be utilizing semantic versioning inside of tron based on Audited releases. [Semantic Versioning](https://semver.org/)
Version strings will be added to the codebase in #58. This ticket will be to generate a process/procedure for how and when the version should be updated.

**Comment by oscarsernarosero** [comment]
During the development of this ticket, [issue 58](https://github.com/thrackle-io/tron/pull/116/files) was also taken care of.
