### ISSUE TITLE
Audit - Fix ToB issue numbers

### ISSUE THREAD

**Issue by ShaneDuncan602** [thrackle-io/forte-rules-engine-v1#74]
ToB removed what was originally issue 16 since it was not truly an issue. By doing so, each subsequent issue number was decremented. All tickets with ToB issues greater than 16 need to be adjusted in both the issue and the related PR.

**Comment by TJ-Everett** [comment]
renamed branches and PRs + left comments in each that needed updates: 
16. Missing validation in publicly callable safeMint (no ticket needed/created) 
17. Inconsistent implementation of risk processing (was issue 18)
18. Batch minting breaks ProtocolERC721Handler rule handling (was issue 19)
19. Access level zero rule checks can be bypassed (was issue 20)
